site_name: stream-read-xbrl
repo_name: uktrade/stream-read-xbrl
repo_url: https://github.com/uktrade/stream-read-xbrl
theme:
  name: tech_docs_template
  logo: assets/dit-logo.png
  favicon: assets/dit-favicon.png
  features:
    - content.code.copy
    - navigation.sections
markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - material/search
nav:
    - Introduction: 'index.md'
    - Usage:
      - Getting started: 'getting-started.md'
      - Data dictionary: 'data-dictionary.md'
      - How data is extracted: 'how-data-is-extracted.md'
      - Investigating data: 'investigating-data.md'
    - Contributing:
      - How to contribute: 'contributing.md'